### ISSUE TITLE
NOT WORKING

### ISSUE THREAD

**Issue by kamleshwebtech** [LaravelDaily/QuickAdminPanel-ExpenseManager#20]
This application does not work with PHP 8.x version. I have tried `composer install` and `composer update`, both are returning the error 

`Root composer.json requires php ^7.3 but your php version (8.0.8) does not satisfy that requirement.`

Need to update the laravel version to make it compatible with latest php version. Thanks to share the code.

**Comment by PovilasKorop** [comment]
@kamleshwebtech yes this is an old demo application and at this moment we don't have plans to upgrade it, focused on other projects
