### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by Andrefly** [LaravelDaily/QuickAdminPanel-ExpenseManager#7]
I clone with git but I don't have .env example?
How can I do?
Do you have any guide that explicate how to install?
Thank you

**Comment by PovilasKorop** [comment]
@Andrefly .env.example is usually a hidden file, so try to open your folder with hidden files.

**Comment by PovilasKorop** [comment]
In repository it surely exists: https://www.github.com/LaravelDaily/QuickAdminPanel-ExpenseManager/tree/master/.env.example
